name: 'CRAN-like publish'
description: 'Publish R package to a CRAN-like repository via SSH'
author: 'Fabien Ors'

inputs:
  package-id:
    description: 'R Package artefact identifer to be published'
  host:
    description: 'CRAN-like server where you can execute SSH commands'
  username:
    description: 'Username for SSH connection'
  password:
    description: 'Password for SSH connection'
  repo-path:
    description: 'Path to the CRAN-like repository in the server'

runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.package-id }}
    
    - name: Retrieve package artefact
      run: |
        PKG_NAME=$(ls -1)
        echo "Artefact retrieved: $PKG_NAME"
        echo "MY_PKG=$PKG_NAME" >> "$GITHUB_ENV"
      shell: bash
      
    - name: Upload to the CRAN-like server
      uses: appleboy/scp-action@master
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        source: ${{ env.MY_PKG }}
        target: ~/

    - name: Updating the packages index of the CRAN-like server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        script: Rscript -e 'drat::insertPackages(${{ env.MY_PKG }}, repodir="${{ inputs.repo-path }}")'

