name: 'CRAN-like publish'
description: 'Publish R packages to a CRAN-like repository via artifacts and SSH'
author: 'Fabien Ors'

inputs:
  host:
    description: 'CRAN server where you can execute SSH commands'
  username:
    description: 'Username for SSH connection'
  password:
    description: 'Password for SSH connection'
  repo-path:
    description: 'Full path to the CRAN repository in the server'
    default: "~"
  pattern:
    description: 'File name pattern filter'
    default: "*"
    
runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v3
      # Downloading several artifacts:
      # https://github.com/actions/download-artifact/issues/103#issuecomment-1290368250
      with:
        path: download_artifacts
    
    - name: Retrieve the list of R packages (all artifacts)
      # For join_by function: https://stackoverflow.com/a/17841619/3952924
      run: |
        ls -ls download_artifacts/*/${{ inputs.pattern }}
        flist=$(ls download_artifacts/*/${{ inputs.pattern }})
        function join_by { local IFS="$1"; shift; echo "$*"; }
        flist=$(join_by , $flist)
        echo "Artifacts retrieved: $flist"
        echo "PKG_LIST=$flist" >> "$GITHUB_ENV"
      shell: bash
      
    - name: Upload all packages to the CRAN-like server
      uses: appleboy/scp-action@master
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        source: ${{ env.PKG_LIST }}
        target: ~/

    - name: Insert each package in the CRAN-like server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ inputs.host }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        script: Rscript -e 'for (p in strsplit("${{ env.PKG_LIST }}", ",")[[1]]) { drat::insertPackages(p, repodir="${{ inputs.repo-path }}") }'

